const root=document.getElementById('app');
let token=localStorage.getItem('token');
let state={teacher:null,students:[],content:[],results:[]};
let recognition=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch('/api'+url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function authView(){root.innerHTML=`<main class="center"><section class="card"><h1>Tuition Teacher App</h1><p>Teacher Login</p><form id="login"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><button>Login</button></form><hr><p>Create new Teacher ID</p><form id="reg"><input name="name" placeholder="Teacher name" required><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><button>Create Account</button></form></section></main>`;login.onsubmit=async e=>{e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(login)))});token=d.token;localStorage.token=token;boot()}catch(x){alert(x.message)}};reg.onsubmit=async e=>{e.preventDefault();try{const d=await api('/auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(reg)))});token=d.token;localStorage.token=token;boot()}catch(x){alert(x.message)}}}
async function load(){[state.teacher,state.students,state.content,state.results]=await Promise.all([api('/me'),api('/students'),api('/content'),api('/results')])}
function dashboard(){root.innerHTML=`<header><b>Tuition Teacher App</b><button id="logout">Logout</button></header><main><section class="grid"><div class="card"><h2>Students</h2><p>${state.students.length}/20</p><button id="addStudent">Add Student</button><div id="studentList">${state.students.map((s,i)=>`<button class="list" data-s="${s.id}">${i+1}. ${esc(s.name)} — Class ${esc(s.class_name)}</button>`).join('')||'<p>No students yet.</p>'}</div></div><div class="card"><h2>Performance</h2>${state.results.map((r,i)=>`<div class="result"><b>#${i+1} ${esc(r.name)}</b><span>${r.score}% · ${r.tests} tests</span></div>`).join('')||'<p>No test results yet.</p>'}</div></section><section class="card"><h2>Content</h2><button id="addSubject">Create Subject</button><div id="content">${renderContent()}</div></section></main>`;logout.onclick=()=>{localStorage.clear();location.reload()};addStudent.onclick=addStudentForm;addSubject.onclick=addSubjectForm;document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>studentTests(+b.dataset.s))}
function renderContent(){return state.content.map(s=>`<div class="subject"><h3>${esc(s.name)}</h3><button onclick="addBookForm(${s.id})">+ Book</button>${s.books.map(b=>`<div class="book"><b>${esc(b.name)}</b><button onclick="addChapterForm(${b.id})">+ Chapter</button>${b.chapters.map(c=>`<div class="chapter"><b>${esc(c.name)}</b> <small>${c.paragraphs.length} paragraphs · ${c.qa.length} Q&A</small><button onclick="editChapter(${c.id})">Open</button></div>`).join('')}</div>`).join('')}</div>`).join('')||'<p>No subjects yet.</p>'}
async function refresh(){await load();dashboard()}
async function addStudentForm(){const name=prompt('Student name');if(!name)return;const className=prompt('Class');if(!className)return;try{await api('/students',{method:'POST',body:JSON.stringify({name,className})});await refresh()}catch(e){alert(e.message)}}
async function addSubjectForm(){const name=prompt('Subject name');if(!name)return;try{await api('/subjects',{method:'POST',body:JSON.stringify({name})});await refresh()}catch(e){alert(e.message)}}
async function addBookForm(subjectId){const name=prompt('Book name');if(!name)return;try{await api('/books',{method:'POST',body:JSON.stringify({subjectId,name})});await refresh()}catch(e){alert(e.message)}}
async function addChapterForm(bookId){const name=prompt('Chapter name');if(!name)return;const text=prompt('Paste full chapter text. Blank lines/new lines will create paragraphs.');if(text===null)return;try{await api('/chapters',{method:'POST',body:JSON.stringify({bookId,name,text})});await refresh()}catch(e){alert(e.message)}}
function studentTests(id){const s=state.students.find(x=>x.id===id);const chapters=state.content.flatMap(x=>x.books.flatMap(b=>b.chapters));root.innerHTML=`<header><b>${esc(s.name)} — Class ${esc(s.class_name)}</b><button onclick="refresh()">Back</button></header><main><section class="card"><h2>Select Test</h2>${chapters.map(c=>`<div class="testrow"><b>${esc(c.name)}</b><span>${c.paragraphs.length} paragraphs · ${c.qa.length} Q&A</span><button onclick="startParagraphTest(${id},${c.id})">Paragraph Test</button><button onclick="startQaTest(${id},${c.id})" ${c.qa.length?'':'disabled'}>Q&A Test</button><button onclick="startChapterTest(${id},${c.id})" ${c.paragraphs.length?'':'disabled'}>Complete Chapter</button></div>`).join('')||'<p>No chapters yet.</p>'}</section></main>`}
function getChapter(id){return state.content.flatMap(s=>s.books.flatMap(b=>b.chapters)).find(c=>c.id===id)}
function tokenize(s){return (s||'').normalize('NFKC').match(/[\p{L}\p{M}\p{N}]+(?:['’-][\p{L}\p{M}\p{N}]+)*/gu)||[]}
function renderWords(reference,matched){const set=new Set(matched||[]);let i=0;return tokenize(reference).map(w=>{const cls=set.has(i)?'word correct':'word';const html=`<span class="${cls}">${esc(w)}</span>`;i++;return html}).join(' ')}
function speakTest({studentId,chapterId,type,itemId,reference,title,onDone}){if(recognition){try{recognition.stop()}catch{}};const total=tokenize(reference).length;root.innerHTML=`<header><b>${esc(title)}</b><button id="exit">Exit</button></header><main><section class="card test"><div class="progress"><b>Test</b><span>${total} words</span></div><p>Start Test दबाने के बाद original text छिप जाएगा। उसके बाद microphone में paragraph/answer बोलें।</p><button id="start">Start Test</button><div id="live"></div><div id="score"></div></section></main>`;exit.onclick=()=>{if(recognition){try{recognition.stop()}catch{}};refresh()};start.onclick=()=>{start.style.display='none';beginRecognition({studentId,chapterId,type,itemId,reference,title,onDone})}}
function beginRecognition({studentId,chapterId,type,itemId,reference,title,onDone}){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){live.innerHTML='<p>इस browser में Speech Recognition उपलब्ध नहीं है। Chrome Android इस्तेमाल करें।</p>';return}live.innerHTML='<p id="status">Listening… बोलना शुरू करें।</p><button id="stop">Stop Test</button><div id="spoken"></div>';let finalParts=[];let stopped=false;recognition=new SR();recognition.continuous=true;recognition.interimResults=true;const hasHindi=/[\u0900-\u097F]/.test(reference);const hasLatin=/[A-Za-z]/.test(reference);recognition.lang=hasHindi?'hi-IN':'en-IN';recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript.trim();if(e.results[i].isFinal){if(t)finalParts.push(t)}else interim+=(t+' ')}const shown=(finalParts.join(' ')+' '+interim).trim();spoken.textContent=shown;status.textContent='Listening…';};recognition.onerror=e=>{if(e.error!=='aborted')status.textContent='Speech error: '+e.error};recognition.onend=()=>{if(!stopped){try{recognition.start()}catch{}}};const finish=async()=>{if(stopped)return;stopped=true;try{recognition.stop()}catch{};const spokenText=finalParts.join(' ').trim();if(!spokenText){status.textContent='कोई speech detect नहीं हुई।';return}status.textContent='Checking…';try{const r=await api('/tests/score',{method:'POST',body:JSON.stringify({studentId,chapterId,testType:type,itemId,spokenText})});score.innerHTML=`<h3>Score: ${r.percent}%</h3><p>${r.correct}/${r.total} words correct — <b>${r.passed?'PASS':'NOT PASS'}</b></p><div class="word-result">${renderWords(r.referenceText,r.matched)}</div><p class="muted">हरे/marked शब्द सही match हुए हैं।</p><button id="nextButton">${onDone?'Next':'Done'}</button>`;document.getElementById('nextButton').onclick=()=>onDone?onDone(r):refresh()}catch(e){alert(e.message);status.textContent=e.message}};stop.onclick=finish;try{recognition.start()}catch(e){status.textContent='Microphone start failed: '+e.message}}
function startParagraphTest(sid,cid){const c=getChapter(cid);if(!c?.paragraphs.length)return alert('No paragraphs');let index=0;const run=()=>{const p=c.paragraphs[index];speakTest({studentId:sid,chapterId:cid,type:'paragraph',itemId:p.id,reference:p.text,title:`${c.name} — Paragraph ${index+1} of ${c.paragraphs.length}`,onDone:()=>{index++;if(index<c.paragraphs.length)run();else showChapterReady(sid,cid)}})};run()}
function showChapterReady(sid,cid){const c=getChapter(cid);root.innerHTML=`<header><b>${esc(c.name)}</b><button onclick="refresh()">Exit</button></header><main><section class="card"><h2>All Paragraphs Completed</h2><p>अब पूरा chapter test दिया जा सकता है।</p><button onclick="startChapterTest(${sid},${cid})">Start Complete Chapter Test</button></section></main>`}
function startQaTest(sid,cid){const c=getChapter(cid);if(!c?.qa.length)return alert('No Q&A');let index=0;const run=()=>{const q=c.qa[index];speakTest({studentId:sid,chapterId:cid,type:'qa',itemId:q.id,reference:q.answer,title:`Q&A ${index+1} of ${c.qa.length} — ${q.question}`,onDone:()=>{index++;if(index<c.qa.length)run();else refresh()}})};run()}
function startChapterTest(sid,cid){const c=getChapter(cid);const reference=c.paragraphs.map(p=>p.text).join(' ');if(!reference)return alert('No paragraph content');speakTest({studentId:sid,chapterId:cid,type:'chapter',reference,title:c.name+' — Complete Chapter Test'})}
function editChapter(cid){const c=getChapter(cid);root.innerHTML=`<header><b>${esc(c.name)}</b><button onclick="refresh()">Back</button></header><main><section class="card"><h2>Paragraphs</h2><p class="muted">Text edit करें। Next paragraph से merge करने का option भी है।</p>${c.paragraphs.map((p,i)=>`<div class="para"><textarea id="p${p.id}">${esc(p.text)}</textarea><div><button onclick="savePara(${p.id})">Save</button>${i<c.paragraphs.length-1?`<button onclick="mergePara(${p.id},${c.paragraphs[i+1].id})">Merge with next</button>`:''}</div></div>`).join('')}<button onclick="addPara(${cid})">+ Add Paragraph</button></section><section class="card"><h2>Add Q&A</h2><input id="q" placeholder="Question"><textarea id="a" placeholder="Correct answer"></textarea><button onclick="addQA(${cid})">Add Q&A</button></section>${c.qa.length?`<section class="card"><h2>Existing Q&A</h2>${c.qa.map(x=>`<div class="qa"><b>${esc(x.question)}</b><p>${esc(x.answer)}</p></div>`).join('')}</section>`:''}</main>`}
async function savePara(id){try{await api('/paragraphs/'+id,{method:'PUT',body:JSON.stringify({text:document.getElementById('p'+id).value})});await refresh()}catch(e){alert(e.message)}}
async function mergePara(firstId,secondId){if(!confirm('इन दोनों paragraphs को एक में merge करें?'))return;try{await api('/paragraphs/merge',{method:'POST',body:JSON.stringify({firstId,secondId})});await refresh()}catch(e){alert(e.message)}}
async function addPara(cid){const text=prompt('New paragraph text');if(!text)return;try{await api('/chapters/'+cid+'/paragraphs',{method:'POST',body:JSON.stringify({text})});await refresh()}catch(e){alert(e.message)}}
async function addQA(cid){if(!q.value||!a.value)return alert('Question और answer दोनों भरें');try{await api('/chapters/'+cid+'/qa',{method:'POST',body:JSON.stringify({question:q.value,answer:a.value})});await refresh()}catch(e){alert(e.message)}}
async function boot(){try{await load();dashboard()}catch(e){localStorage.clear();authView()}}
boot();
